### ISSUE TITLE
合成数据中的n_class表示什么？

### ISSUE THREAD

**Issue by limaofuyuanzhang** [nd009/digit_recognition#1]
import numpy as np
from sklearn.model_selection import train_test_split

n_class, n_len, width, height = 11, 5, 28, 28

def generate_dataset(X, y):
    X_len = X.shape[0]
    
    X_gen = np.zeros((X_len, height, width*n_len, 1), dtype=np.uint8)
    y_gen = [np.zeros((X_len, n_class), dtype=np.uint8) for i in range(n_len)]
    # TODO: 随机取1~5个数字，并拼接成新的图片
    
    y_gen = np.asarray([labels_1,labels_2,labels_3,labels_4,labels_5])
    
    return X_gen, y_gen

X_raw_train, X_raw_valid, y_raw_train, y_raw_valid = train_test_split(X_raw,y_raw,test_size=20,random_state=0)

X_train, y_train = generate_dataset(X_raw_train, y_raw_train)
X_valid, y_valid = generate_dataset(X_raw_valid, y_raw_valid)
X_test, y_test = generate_dataset(X_raw_test, y_raw_test)

P5合成数据这问中，里面的n_class代表什么？为什么它的值是11？y_gen为什么是这样一个结构？我的理解是按目前的X_gen的结构，y_gen不是应该是一个(5,X_len)就可以了吗？

**Comment by ypwhs** [comment]
(5,X_len) 的话，你可以思考一下，第一条数据应该长什么样，如果是[1, 2, 3, 10, 10]，那就是一个回归问题了，但是我们应该做一个分类问题，所以应该是 (5, X_len, 11)，11代表 10个数字+空白类
